/**
 * Centralized UI labels — single source of truth for all visible text strings.
 * Only change visible UI labels here; never variable names, route paths, or data attributes.
 */
export const LABELS = {
  task: {
    singular: 'Task',
    plural: 'Tasks',
    postingDate: 'Posting Date',
    dueDate: 'Due Date',
    deadline: 'Deadline',
    status: 'Status',
    caption: 'Caption',
    designFile: 'Design File',
    briefing: 'Briefing',
    assignee: 'Assignee',
    create: 'Create Task',
    creating: 'Creating...',
    saved: 'Task saved.',
    deleted: 'Delete task',
    deleteConfirm: 'Delete this task? This also removes the current design file.',
    noDate: 'No date',
  },
  project: {
    singular: 'Project',
    plural: 'Projects',
    active: 'Active',
    create: 'Create Project',
    creating: 'Create Project',
  },
  client: {
    singular: 'Client',
    plural: 'Clients',
    create: 'Add Client',
    createTitle: 'Create client',
    createDescription:
      'Add a client by name only. A unique slug is generated automatically for portal access.',
    shareLink: 'Share Link',
  },
  teamMember: {
    singular: 'Team Member',
    plural: 'Team Members',
  },
  dashboard: {
    totalProjects: 'Total Active Projects',
    tasksInProgress: 'Tasks In Progress',
    overdueTasks: 'Overdue Tasks',
    completedThisMonth: 'Completed This Month',
    team: {
      totalAssigned: 'Total Assigned',
      dueToday: 'Due Today',
      overdue: 'Overdue',
      completed: 'Completed',
    },
  },
  emptyStates: {
    noClients: 'No clients yet',
    noProjects: 'No projects yet. Create the first one.',
    noTasks: 'No tasks yet. Create the first task to populate this project.',
    noTasksAssigned: 'No tasks assigned yet.',
    noDesignFile: 'No design file uploaded yet.',
    noCaption: 'No caption has been added yet.',
    noPortalTasks: 'No tasks with posting dates are available yet.',
    noDate: 'No date',
    noTasksInColumn: 'No tasks.',
    noTasksScheduled: 'No tasks are scheduled yet for this active project.',
  },
  copy: {
    label: 'Copy',
    copied: 'Copied',
    confirmation: 'Copied to clipboard.',
  },
  notify: {
    title: 'Notify Assigner',
    description:
      'This will notify the admin that your work is complete and mark the task as done.',
    button: 'Notify Assigner',
    success: 'Assigner notified and task marked as done.',
    confirmButton: 'Confirm and mark done',
    assigning: 'Assigning...',
  },
  share: {
    copied: 'Link copied.',
    copyAction: 'Share Link',
    tooltip: 'Copy portal share link',
  },
  common: {
    adminPanel: 'Management Panel',
    edit: 'Edit',
    delete: 'Delete',
    deleteTask: 'Delete task',
    cancel: 'Cancel',
    create: 'Create',
    save: 'Save',
    saving: 'Saving...',
    back: 'Back',
    close: 'Close',
    actions: 'Actions',
    title: 'Title',
    status: 'Status',
    name: 'Name',
    month: 'Month',
    year: 'Year',
    assignedTo: 'Assigned to',
    monthPlaceholder: 'April Content Plan',
    projectList: 'Client projects',
    projectDescription: 'Manage monthly project cycles for this client.',
  },
  kanban: {
    columns: {
      todo: 'To Do',
      in_progress: 'In Progress',
      done: 'Done',
    },
  },
  comments: {
    title: 'Comments',
    placeholder: 'Add a comment...',
    submit: 'Post comment',
    submitting: 'Posting...',
    revisionBadge: 'Revision Requested',
    empty: 'No comments yet.',
    posted: 'Comment posted.',
    errorEmpty: 'Comment must not be empty',
  },
} as const
